// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXNuhqNXLzHgjJtrEX4WRIpaGowasLY0k',
    appId: '1:322776854127:web:63710d72ac5653ec8fe79a',
    messagingSenderId: '322776854127',
    projectId: 'aghieri-7a8ce',
    authDomain: 'aghieri-7a8ce.firebaseapp.com',
    storageBucket: 'aghieri-7a8ce.firebasestorage.app',
    measurementId: 'G-H7CSNLKXKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMiAkjSsBQJFypVbb3xsQ79F7sXTsDp4k',
    appId: '1:322776854127:android:fb9e30296388172e8fe79a',
    messagingSenderId: '322776854127',
    projectId: 'aghieri-7a8ce',
    storageBucket: 'aghieri-7a8ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChcZcbgwxWr59EnIPFilcfwueOsd-XFiw',
    appId: '1:322776854127:ios:b5f0fdcca885d8ae8fe79a',
    messagingSenderId: '322776854127',
    projectId: 'aghieri-7a8ce',
    storageBucket: 'aghieri-7a8ce.firebasestorage.app',
    iosBundleId: 'com.toakco.aghieri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChcZcbgwxWr59EnIPFilcfwueOsd-XFiw',
    appId: '1:322776854127:ios:b5f0fdcca885d8ae8fe79a',
    messagingSenderId: '322776854127',
    projectId: 'aghieri-7a8ce',
    storageBucket: 'aghieri-7a8ce.firebasestorage.app',
    iosBundleId: 'com.toakco.aghieri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXNuhqNXLzHgjJtrEX4WRIpaGowasLY0k',
    appId: '1:322776854127:web:ba984cd177552d038fe79a',
    messagingSenderId: '322776854127',
    projectId: 'aghieri-7a8ce',
    authDomain: 'aghieri-7a8ce.firebaseapp.com',
    storageBucket: 'aghieri-7a8ce.firebasestorage.app',
    measurementId: 'G-6ZELJECB98',
  );
}
